"""sync_schema_v2

Revision ID: 7919951fa9d1
Revises: ada769d0d0a8
Create Date: 2025-12-07 14:57:24.673726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7919951fa9d1'
down_revision: Union[str, Sequence[str], None] = 'ada769d0d0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.alter_column('occurred_at_utc',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_mood_logs_log_date'))
        batch_op.create_index(batch_op.f('ix_mood_logs_occurred_at_utc'), ['occurred_at_utc'], unique=False)

    with op.batch_alter_table('sleep_logs', schema=None) as batch_op:
        batch_op.alter_column('occurred_at_utc',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_sleep_logs_log_date'))
        batch_op.create_index(batch_op.f('ix_sleep_logs_occurred_at_utc'), ['occurred_at_utc'], unique=False)

    with op.batch_alter_table('stress_logs', schema=None) as batch_op:
        batch_op.alter_column('occurred_at_utc',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_stress_logs_log_date'))
        batch_op.create_index(batch_op.f('ix_stress_logs_occurred_at_utc'), ['occurred_at_utc'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stress_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stress_logs_occurred_at_utc'))
        batch_op.create_index(batch_op.f('ix_stress_logs_log_date'), ['occurred_at_utc'], unique=False)
        batch_op.alter_column('occurred_at_utc',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('sleep_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sleep_logs_occurred_at_utc'))
        batch_op.create_index(batch_op.f('ix_sleep_logs_log_date'), ['occurred_at_utc'], unique=False)
        batch_op.alter_column('occurred_at_utc',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mood_logs_occurred_at_utc'))
        batch_op.create_index(batch_op.f('ix_mood_logs_log_date'), ['occurred_at_utc'], unique=False)
        batch_op.alter_column('occurred_at_utc',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
