"""Add chat tables

Revision ID: ada769d0d0a8
Revises: 012_add_menu_item_allergens_association
Create Date: 2025-12-01 20:54:02.350750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada769d0d0a8'
down_revision: Union[str, Sequence[str], None] = '012_add_menu_item_allergens_association'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.alter_column('mood_logs', 'occurred_at_utc',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_mood_logs_log_date'), table_name='mood_logs')
    op.create_index(op.f('ix_mood_logs_occurred_at_utc'), 'mood_logs', ['occurred_at_utc'], unique=False)
    op.alter_column('sleep_logs', 'occurred_at_utc',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sleep_logs_log_date'), table_name='sleep_logs')
    op.create_index(op.f('ix_sleep_logs_occurred_at_utc'), 'sleep_logs', ['occurred_at_utc'], unique=False)
    op.alter_column('stress_logs', 'occurred_at_utc',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.drop_index(op.f('ix_stress_logs_log_date'), table_name='stress_logs')
    op.create_index(op.f('ix_stress_logs_occurred_at_utc'), 'stress_logs', ['occurred_at_utc'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stress_logs_occurred_at_utc'), table_name='stress_logs')
    op.create_index(op.f('ix_stress_logs_log_date'), 'stress_logs', ['occurred_at_utc'], unique=False)
    op.alter_column('stress_logs', 'occurred_at_utc',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sleep_logs_occurred_at_utc'), table_name='sleep_logs')
    op.create_index(op.f('ix_sleep_logs_log_date'), 'sleep_logs', ['occurred_at_utc'], unique=False)
    op.alter_column('sleep_logs', 'occurred_at_utc',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_mood_logs_occurred_at_utc'), table_name='mood_logs')
    op.create_index(op.f('ix_mood_logs_log_date'), 'mood_logs', ['occurred_at_utc'], unique=False)
    op.alter_column('mood_logs', 'occurred_at_utc',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
